version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 

executors:
  ruby_3_0:
    docker:
      - image: circleci/ruby:3.0-browsers-legacy
  ruby_2_7:
    docker:
      - image: circleci/ruby:2.7-browsers-legacy
  ruby_2_6:
    docker:
      - image: circleci/ruby:2.6-browsers-legacy
  ruby_2_5:
    docker:
      - image: circleci/ruby:2.5-browsers-legacy
  ruby_2_3:
    docker:
      - image: circleci/ruby:2.3-browsers-legacy

jobs:
  test:
    parameters:
      rails_version:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    environment:
      RAILS_VERSION=<< parameters.rails_version >>
    steps:
      - checkout:
         path: jasmine-gem
      - run:
          name: Install Node
          command: sudo apt update && sudo apt-get install nodejs
      - run:
          name: Install bundler
          command: "if [ $RAILS_VERSION = rails4 ];then gem install bundler -v '< 2.0' ; else gem install bundler; fi"
      - run:
          name: Report versions
          command: "echo 'Ruby version:' && ruby -v && echo 'Bundler version:' && bundle -v && echo 'RAILS_VERSION:' $RAILS_VERSION"
      - run:
          name: Install gems
          command: "cd jasmine-gem && bundle install"
      - run:
          name: Run tests
          command: "cd jasmine-gem && bundle exec rake --trace"

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - test:
          matrix:
            parameters:
              rails_version: ["pojs", "rails6", "rails5", "rails4"]
              executor: ["ruby_3_0", "ruby_2_7", "ruby_2_6", "ruby_2_5", "ruby_2_3"]
            exclude:
              # Don't run Rails 4 on newer Rubies that lack an old enough
              # bundler.
              - rails_version: "rails4"
                executor: "ruby_3_0"
              - rails_version: "rails4"
                executor: "ruby_2_7"
              # Rails 6 requires at least Ruby 2.5.
              - rails_version: "rails6"
                executor: "ruby_2_3"
              # Rails 5 requires Ruby < 2.7
              - rails_version: "rails5"
                executor: "ruby_3_0"
              - rails_version: "rails5"
                executor: "ruby_2_7"
  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 10 * * *"
          filters:
            branches:
               only:
                 - main
